server:
  port: 8080

spring:
  redis:
    host: 192.168.1.12
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.12:3306/test?useSSL=false
    username: springbootuser
    password: Messi$001
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
